### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by psifertex** [xpcmdshell/SysctlHunter#2]
One suggestion as I just noticed the `plistlib` dependency. We haven't documented it much yet, but if you create a [requirements.txt](https://github.com/Vector35/snippets/blob/master/requirements.txt) BN can auto-install dependencies which is nice since otherwise people testing this will have to manually install it.

**Comment by xpcmdshell** [comment]
Plistlib is actually one of the core python modules, so it should be included by default ([at least it appears to be that way for Python 3](https://docs.python.org/3.7/library/plistlib.html#module-plistlib)). I can definitely add a requirements.txt in future versions if there's external module dependencies though

**Comment by psifertex** [comment]
Oh, fair enough! Sorry about that, I assumed it wouldn't be with such a specific function and only for macosx files but that works too, ignore me. :-)
